In [2]:
pip install pandas

     ---------------------------------------- 10.4/10.4 MB 1.4 MB/s eta 0:00:00
     ------------------------------------ 498.1/498.1 kB 636.8 kB/s eta 0:00:00
     ---------------------------------------- 14.6/14.6 MB 1.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import pandas as pd

data = pd.read_csv('Cleaned_Car_data.csv')

print(data.head())

   Unnamed: 0                    name   company  year   Price  kms_driven  \
0           0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1           1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2           2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3           3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4           4               Ford Figo      Ford  2012  175000       41000   

  fuel_type  
0    Petrol  
1    Diesel  
2    Petrol  
3    Diesel  
4    Diesel  


In [14]:
y = list(map(lambda v: 'yes' if v == 1 else 'no', data['fuel_type'].values)) # target values as string

X = data[['name','company','year','kms_driven']].values # features values

In [15]:
print(len(y)) # >> 887

y_train = y[:600]
y_val = y[600:]

X_train = X[:600]
X_val = X[600:]

816


In [16]:
## Creating the Naive Bayes Classifier instance with the training data

nbc = NaiveBayesClassifier(X_train, y_train)


total_cases = len(y_val) # size of validation set

# Well classified examples and bad classified examples
good = 0
bad = 0

for i in range(total_cases):
    predict = nbc.classify(X_val[i])
#     print(y_val[i] + ' --------------- ' + predict)
    if y_val[i] == predict:
        good += 1
    else:
        bad += 1

print('TOTAL EXAMPLES:', total_cases)
print('RIGHT:', good)
print('WRONG:', bad)
print('ACCURACY:', good/total_cases)

TOTAL EXAMPLES: 216
RIGHT: 216
WRONG: 0
ACCURACY: 1.0


In [2]:
import pandas as pd
df = pd.read_csv("Cleaned_Car_data.csv")
df.head

<bound method NDFrame.head of      Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
811         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
812         812          Tata Indica V2      Tata  2009  110000       30000   
813         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
814         814            Tata Zest XM      Tata  2018  260000       27000   
815         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  
0    

In [6]:
df.groupby('fuel_type').describe()

Unnamed: 0                                                        \
               count        mean         std    min     25%    50%     75%   
fuel_type                                                                    
Diesel         386.0  402.974093  233.039831    1.0  208.25  387.0  606.50   
LPG              2.0  521.500000   89.802561  458.0  489.75  521.5  553.25   
Petrol         428.0  411.049065  238.665170    0.0  195.75  425.5  615.25   

                   year               ...  LPG      Diesel                 \
             max  count         mean  ...  75%  max  count mean  std  min   
fuel_type                             ...                                   
Diesel     815.0  386.0  2013.253886  ...  0.0  0.0  386.0  0.0  0.0  0.0   
LPG        585.0    2.0  2012.500000  ...  0.0  0.0    2.0  0.0  0.0  0.0   
Petrol     813.0  428.0  2011.714953  ...  0.0  0.0  428.0  0.0  0.0  0.0   

                               
           25%  50%  75%  max  
fuel_type                      
Diesel     0.0  0.0  0.0  0.0  
LPG        0.0  0.0  0.0  0.0  
Petrol     0.0  0.0  0.0  0.0  

[3 rows x 48 columns]

In [10]:
df['Diesel']=df['fuel_type'].apply(lambda x: 1 if x=='Diesel' else 0)
df.head

<bound method NDFrame.head of      Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
811         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
812         812          Tata Indica V2      Tata  2009  110000       30000   
813         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
814         814            Tata Zest XM      Tata  2018  260000       27000   
815         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  LPG  D

In [11]:
df['LPG']=df['fuel_type'].apply(lambda x: 1 if x=='LPG' else 0)
df.head

<bound method NDFrame.head of      Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
811         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
812         812          Tata Indica V2      Tata  2009  110000       30000   
813         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
814         814            Tata Zest XM      Tata  2018  260000       27000   
815         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  LPG  D

In [12]:
df['Petrol']=df['fuel_type'].apply(lambda x: 1 if x=='Petrol' else 0)
df.head

<bound method NDFrame.head of      Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
811         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
812         812          Tata Indica V2      Tata  2009  110000       30000   
813         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
814         814            Tata Zest XM      Tata  2018  260000       27000   
815         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  LPG  D

In [15]:
pip install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
  Running setup.py install for sklearn: started
  Running setup.py install for sklearn: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
pip install sklearn.model

     ---------------------------------------- 8.2/8.2 MB 4.3 MB/s eta 0:00:00
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
     ---------------------------------------- 40.1/40.1 MB 4.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.company,df.Diesel, test_size=0.25)

In [24]:
pip install sklearn.feature


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement sklearn.feature (from versions: none)
ERROR: No matching distribution found for sklearn.feature

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0]], dtype=int64)

In [28]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [34]:
cars = [
    'Renault Duster',
    'Maruti Suzuki Dzire'
]
cars_count = v.transform(cars)
model.predict(cars_count)

array([1, 0], dtype=int64)

In [35]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.7303921568627451

In [36]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [37]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [38]:
clf.score(X_test,y_test)

0.7303921568627451

In [40]:
clf.predict(cars)

array([1, 0], dtype=int64)